version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/special-offer-widget
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
  deploy-job:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/special-offer-widget
    steps:
      - checkout
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: npm run deploy --prod
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master